### ISSUE TITLE
目前已经出现可支持音量键的kext的你也可以试下

### ISSUE THREAD

**Issue by My-czr** [ilharp/surface-pro-4-hackintosh-big-sur#2]
Bigsurface项目支持集成和热插拔触摸板和键盘支持
https://github.com/Xiashangning/BigSurface

**Comment by Afanyiyu** [comment]
非常感谢！之后会试试看的
你已经在 sp4 上测试成功了嘛

**Comment by ilharp** [comment]
经过测试，实体按钮仍无法使用，但触摸板 & 键盘支持确实可以更新。已加装到仓库中。

我留意到作者也说了如果想要支持的话可以与他联系，不过目前实体按钮对我来说不是那么重要，所以我暂时懒得去花时间在这上面了（趴

总之  感谢告知我如此优秀的项目！
